name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          fetch-depth: 0
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c939634d49e1e779a1f337f714652c7714f36

        with:
          args: >
            -Dsonar.projectKey=OlegRakhilov_python-project-50
            -Dsonar.organization=a9282268847
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}